{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "15fa5d0a-64ad-4a91-85ec-1f260f8ab2c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "============================================================\n",
    "  TWEET VIRALITY PREDICTOR — FINAL CLEAN VERSION\n",
    "============================================================\n",
    "\"\"\"\n",
    "\n",
    "# ─── 1. IMPORTS ───────────────────────────────────────────\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import re\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
    "from sklearn.metrics import (\n",
    "    accuracy_score, classification_report, confusion_matrix,\n",
    "    roc_auc_score, roc_curve\n",
    ")\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "import scipy.sparse as sp\n",
    "\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# ─── 2. LOAD DATA ─────────────────────────────────────────\n",
    "print(\"=\" * 60)\n",
    "print(\"  STEP 1: Loading Datasets\")\n",
    "print(\"=\" * 60)\n",
    "\n",
    "dfs = []\n",
    "\n",
    "def load_file(file):\n",
    "    try:\n",
    "        if file.endswith(\".csv\"):\n",
    "            df = pd.read_csv(file, low_memory=False)\n",
    "        elif file.endswith(\".xlsx\"):\n",
    "            df = pd.read_excel(file)\n",
    "        else:\n",
    "            return None\n",
    "        print(f\"  ✅ Loaded {file}: {df.shape[0]:,} rows\")\n",
    "        return df\n",
    "    except:\n",
    "        print(f\"  ❌ Failed to load {file}\")\n",
    "        return None\n",
    "\n",
    "files = [\"data_analysis.csv\", \"data_visualization.csv\", \"data_science.csv\"]\n",
    "\n",
    "for f in files:\n",
    "    df_temp = load_file(f)\n",
    "    if df_temp is not None:\n",
    "        df_temp[\"source_dataset\"] = f\n",
    "        dfs.append(df_temp)\n",
    "\n",
    "if not dfs:\n",
    "    raise RuntimeError(\"No datasets loaded!\")\n",
    "\n",
    "# Align columns safely\n",
    "common_cols = set(dfs[0].columns)\n",
    "for d in dfs[1:]:\n",
    "    common_cols = common_cols & set(d.columns)\n",
    "\n",
    "dfs = [d[list(common_cols)].copy() for d in dfs]\n",
    "\n",
    "df = pd.concat(dfs, ignore_index=True)\n",
    "print(f\"\\n📊 Combined dataset: {df.shape}\")\n",
    "\n",
    "# ─── 3. HANDLE MISSING COLUMNS ────────────────────────────\n",
    "expected_cols = [\n",
    "    \"hashtags\", \"mentions\", \"urls\", \"photos\",\n",
    "    \"video\", \"retweet\", \"replies_count\",\n",
    "    \"likes_count\", \"retweets_count\"\n",
    "]\n",
    "\n",
    "for col in expected_cols:\n",
    "    if col not in df.columns:\n",
    "        df[col] = 0\n",
    "\n",
    "# ─── 4. CLEAN DATA ────────────────────────────────────────\n",
    "df = df[df[\"language\"] == \"en\"].copy()\n",
    "df = df.dropna(subset=[\"tweet\"])\n",
    "\n",
    "for col in [\"likes_count\", \"retweets_count\", \"replies_count\", \"video\"]:\n",
    "    df[col] = pd.to_numeric(df[col], errors=\"coerce\").fillna(0)\n",
    "\n",
    "df[\"created_at\"] = pd.to_datetime(df[\"created_at\"], errors=\"coerce\")\n",
    "df[\"hour\"] = df[\"created_at\"].dt.hour\n",
    "df[\"day_of_week\"] = df[\"created_at\"].dt.dayofweek\n",
    "df[\"month\"] = df[\"created_at\"].dt.month\n",
    "df[\"year\"] = df[\"created_at\"].dt.year\n",
    "\n",
    "# ─── 5. FEATURE ENGINEERING ───────────────────────────────\n",
    "def clean_tweet(text):\n",
    "    text = re.sub(r\"http\\S+\", \"\", str(text))\n",
    "    text = re.sub(r\"@\\w+\", \"\", text)\n",
    "    text = re.sub(r\"#(\\w+)\", r\"\\1\", text)\n",
    "    text = re.sub(r\"[^a-zA-Z\\s]\", \"\", text)\n",
    "    return text.strip().lower()\n",
    "\n",
    "df[\"tweet_clean\"] = df[\"tweet\"].apply(clean_tweet)\n",
    "df[\"tweet_length\"] = df[\"tweet\"].str.len()\n",
    "df[\"word_count\"] = df[\"tweet_clean\"].str.split().str.len()\n",
    "\n",
    "def count_items(val):\n",
    "    if pd.isna(val) or val in (\"[]\", \"\", \"nan\"):\n",
    "        return 0\n",
    "    try:\n",
    "        return len(eval(val)) if isinstance(val, str) else 0\n",
    "    except:\n",
    "        return 0\n",
    "\n",
    "df[\"hashtag_count\"] = df[\"hashtags\"].apply(count_items)\n",
    "df[\"mention_count\"] = df[\"mentions\"].apply(count_items)\n",
    "\n",
    "df[\"has_hashtag\"] = (df[\"hashtag_count\"] > 0).astype(int)\n",
    "df[\"has_mention\"] = (df[\"mention_count\"] > 0).astype(int)\n",
    "df[\"has_url\"] = df[\"urls\"].apply(lambda x: 0 if pd.isna(x) or x in (\"[]\", \"\") else 1)\n",
    "df[\"has_photo\"] = df[\"photos\"].apply(lambda x: 0 if pd.isna(x) or x in (\"[]\", \"\") else 1)\n",
    "df[\"has_video\"] = (df[\"video\"] > 0).astype(int)\n",
    "df[\"is_retweet\"] = df[\"retweet\"].astype(int)\n",
    "\n",
    "# ─── 6. TARGET VARIABLE ───────────────────────────────────\n",
    "df[\"engagement\"] = (\n",
    "    df[\"likes_count\"] +\n",
    "    df[\"retweets_count\"] +\n",
    "    df[\"replies_count\"]\n",
    ")\n",
    "\n",
    "threshold = df[\"engagement\"].quantile(0.75)\n",
    "df[\"viral\"] = (df[\"engagement\"] > threshold).astype(int)\n",
    "\n",
    "print(f\"  Viral threshold (75%): {threshold:.0f}\")\n",
    "\n",
    "# ─── 7. FEATURES ──────────────────────────────────────────\n",
    "META_FEATURES = [\n",
    "    \"tweet_length\", \"word_count\",\n",
    "    \"hashtag_count\", \"mention_count\",\n",
    "    \"has_hashtag\", \"has_mention\", \"has_url\", \"has_photo\",\n",
    "    \"has_video\", \"is_retweet\",\n",
    "    \"hour\", \"day_of_week\", \"month\", \"year\",\n",
    "    \"replies_count\"\n",
    "]\n",
    "\n",
    "X_meta = df[META_FEATURES].fillna(0)\n",
    "X_text = df[\"tweet_clean\"]\n",
    "y = df[\"viral\"]\n",
    "\n",
    "# ─── 8. SPLIT ─────────────────────────────────────────────\n",
    "X_meta_train, X_meta_test, X_text_train, X_text_test, y_train, y_test = train_test_split(\n",
    "    X_meta, X_text, y, test_size=0.2, random_state=42, stratify=y\n",
    ")\n",
    "\n",
    "# ─── 9. TF-IDF ────────────────────────────────────────────\n",
    "tfidf = TfidfVectorizer(max_features=500, stop_words=\"english\", ngram_range=(1, 2))\n",
    "X_tfidf_train = tfidf.fit_transform(X_text_train)\n",
    "X_tfidf_test = tfidf.transform(X_text_test)\n",
    "\n",
    "# Scale metadata (only needed for LR)\n",
    "scaler = StandardScaler()\n",
    "X_meta_train_s = scaler.fit_transform(X_meta_train)\n",
    "X_meta_test_s = scaler.transform(X_meta_test)\n",
    "\n",
    "X_train = sp.hstack([X_tfidf_train, sp.csr_matrix(X_meta_train_s)])\n",
    "X_test = sp.hstack([X_tfidf_test, sp.csr_matrix(X_meta_test_s)])\n",
    "\n",
    "# ─── 10. MODELS ───────────────────────────────────────────\n",
    "results = {}\n",
    "\n",
    "# Logistic Regression\n",
    "lr = LogisticRegression(max_iter=1000)\n",
    "lr.fit(X_train, y_train)\n",
    "results[\"Logistic\"] = {\n",
    "    \"pred\": lr.predict(X_test),\n",
    "    \"prob\": lr.predict_proba(X_test)[:, 1]\n",
    "}\n",
    "\n",
    "# Random Forest\n",
    "rf = RandomForestClassifier(n_estimators=100, max_depth=15, random_state=42)\n",
    "rf.fit(X_train, y_train)\n",
    "results[\"RandomForest\"] = {\n",
    "    \"pred\": rf.predict(X_test),\n",
    "    \"prob\": rf.predict_proba(X_test)[:, 1]\n",
    "}\n",
    "\n",
    "# Gradient Boosting (convert to dense)\n",
    "X_train_dense = X_train.toarray()\n",
    "X_test_dense = X_test.toarray()\n",
    "\n",
    "gb = GradientBoostingClassifier()\n",
    "gb.fit(X_train_dense, y_train)\n",
    "results[\"GradientBoost\"] = {\n",
    "    \"pred\": gb.predict(X_test_dense),\n",
    "    \"prob\": gb.predict_proba(X_test_dense)[:, 1]\n",
    "}\n",
    "\n",
    "# ─── 11. EVALUATION ───────────────────────────────────────\n",
    "print(\"\\nMODEL PERFORMANCE\\n\")\n",
    "\n",
    "best_model = None\n",
    "best_auc = 0\n",
    "\n",
    "for name, res in results.items():\n",
    "    acc = accuracy_score(y_test, res[\"pred\"])\n",
    "    auc = roc_auc_score(y_test, res[\"prob\"])\n",
    "    print(f\"{name}: Accuracy={acc:.4f}, AUC={auc:.4f}\")\n",
    "    \n",
    "    if auc > best_auc:\n",
    "        best_auc = auc\n",
    "        best_model = name\n",
    "\n",
    "print(f\"\\n🏆 BEST MODEL: {best_model}\")\n",
    "\n",
    "print(\"\\nClassification Report:\\n\")\n",
    "print(classification_report(y_test, results[best_model][\"pred\"]))\n",
    "\n",
    "# ─── 12. VISUALIZATION ────────────────────────────────────\n",
    "plt.figure(figsize=(6,4))\n",
    "sns.countplot(x=y)\n",
    "plt.title(\"Viral vs Non-Viral Tweets\")\n",
    "plt.show()\n",
    "\n",
    "# ─── 13. PREDICTION FUNCTION ──────────────────────────────\n",
    "def predict_tweet(text):\n",
    "    clean = clean_tweet(text)\n",
    "    tfidf_feat = tfidf.transform([clean])\n",
    "\n",
    "    meta = pd.DataFrame([{\n",
    "        \"tweet_length\": len(text),\n",
    "        \"word_count\": len(clean.split()),\n",
    "        \"hashtag_count\": text.count(\"#\"),\n",
    "        \"mention_count\": text.count(\"@\"),\n",
    "        \"has_hashtag\": int(\"#\" in text),\n",
    "        \"has_mention\": int(\"@\" in text),\n",
    "        \"has_url\": int(\"http\" in text),\n",
    "        \"has_photo\": 0,\n",
    "        \"has_video\": 0,\n",
    "        \"is_retweet\": 0,\n",
    "        \"hour\": 12,\n",
    "        \"day_of_week\": 2,\n",
    "        \"month\": 6,\n",
    "        \"year\": 2021,\n",
    "        \"replies_count\": 0\n",
    "    }])\n",
    "\n",
    "    meta_scaled = scaler.transform(meta[META_FEATURES])\n",
    "    X_new = sp.hstack([tfidf_feat, sp.csr_matrix(meta_scaled)])\n",
    "\n",
    "    prob = rf.predict_proba(X_new)[0][1]\n",
    "    return \"🔥 Viral\" if prob > 0.5 else \"📉 Not Viral\", prob\n",
    "\n",
    "# Demo\n",
    "tweet = \"Excited to share new AI research! #AI #MachineLearning\"\n",
    "label, prob = predict_tweet(tweet)\n",
    "\n",
    "print(\"\\nDemo Prediction:\")\n",
    "print(tweet)\n",
    "print(label, prob)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "software_modeling",
   "language": "python",
   "name": "software_modeling"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
